Feature/mana system
Team-Swamp/Adley-s_Adventure pull request #3
Opened 2022-07-20 00:19 UTC by MsZoezo

Basic mana systeem is af, je kan mana gebruiken en toevoegen.

2022-07-21 17:51 UTC, bas-boop requested changes

2022-07-21 17:51 UTC, bas-boop commented on Assets/Magic/Mana.cs
> +    [SerializeField] private float maxMana;
```suggestion
{
    [Header("Event Variables")]
    [SerializeField] private UnityEvent onFull= new UnityEvent();
    [SerializeField] private UnityEvent onEmpty = new UnityEvent();
    
    [SerializeField] private float maxMana;
```

Misshien deze unity events er in krijgen. Kan handig zijn voor later.

2022-07-21 17:51 UTC, bas-boop commented on Assets/Magic/Mana.cs
> +    /// </example>
```suggestion

```
Het voorbeeld hoef er niet perse in, de code is leesbaar. Ook heb je het <returns> ding, dus dat zal wel duidelijk genoeg zijn.

2022-07-21 17:51 UTC, bas-boop commented on Assets/Magic/Mana.cs
> +        if (_mana - expendedMana < 0f) return false;
```suggestion
        if (_mana - expendedMana < minimaleMana) return false;
```
ipv een 0f neer te zetten, boven aan een [SerializeField] float neer te zetten.

2022-07-21 17:51 UTC, bas-boop commented on Assets/Magic/Mana.cs
> +        _mana = Mathf.Clamp(_mana + addedMana, 0f, maxMana);
```suggestion
        _mana = Mathf.Clamp(_mana + addedMana, minimaleMana, maxMana);
```

2022-07-21 17:51 UTC, bas-boop commented on Assets/Magic/Mana.cs
> +    [SerializeField] private float maxMana;
```suggestion
    [SerializeField] private float maxMana;
    [SerializeField] private float minimaleMana;
```

2022-07-23 01:14 UTC, MsZoezo commented on Assets/Magic/Mana.cs
> +    [SerializeField] private float maxMana;
UnityEvents Toegevoegd in [69a2582](https://github.com/Team-Swamp/Adley-s_Adventure/pull/3/commits/69a258275ee66e53690c6a989e3923e8396a257a)

2022-07-23 10:53 UTC, bas-boop approved these changes

2022-07-23 15:23 UTC, Tatum13 approved these changes

2022-07-23 15:24 UTC, merged