mana regeneration added with interval
Team-Swamp/Adley-s_Adventure pull request #8
Opened 2022-07-23 20:05 UTC by MsZoezo

2022-07-23 22:33 UTC, Tatum13 commented on Assets/Scripts/Magic/Mana.cs
> +    [SerializeField] private float regenAmount;
```suggestion
    [SerializeField] private float regenerationInterval;
    [SerializeField] private float regenerationCooldown;
    [SerializeField] private float regenerationAmount;
```

2022-07-24 13:09 UTC, bas-boop commented on Assets/Scripts/Magic/Mana.cs
> +    [SerializeField] private float regenAmount;
Naar mijn mening is het wel duidelijk, dus hoef niet perse.

2022-07-24 18:25 UTC, bas-boop approved these changes

2022-08-05 18:36 UTC, bas-boop requested changes

2022-08-05 18:36 UTC, bas-boop commented on Assets/Scripts/Magic/Mana.cs
> +
```suggestion
    [SerializeField] private float regenInterval;
    [SerializeField] private float regenCooldown;
    [SerializeField] private float regenAmount;
    
    [SerializeField] private UnityEvent onStartRegen = new UnityEvent(); 
```

2022-08-05 18:38 UTC, bas-boop commented on Assets/Scripts/Magic/Mana.cs
> +
wel deze unity event bij de andere bovenin neer zetten

2022-08-14 21:42 UTC, bas-boop approved these changes
Okie dokie

2022-08-14 21:44 UTC, Tatum13 approved these changes

2022-08-14 21:45 UTC, merged